services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Examplepassword123
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
